version: '3.7'
services:
  # web:
  #   build: .
  #   container_name: aspnet-core-webapi
  #   restart: always
  #   ports:
  #     - "8181:80"
  #   links:
  #     - mongodb
  #     - mysqldb
  #   depends_on:
  #     - mongodb
  #     - mysqldb
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
  mysqldb:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysqldb"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"