version: '3.7'
services:
  web:
    build: .
    container_name: aspnet-core-webapi
    ports:
      - "8181:80"
    links:
      - mongodb
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aspnet-core-webapi/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017