version: '3.3'

services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"

  mysqldb:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysqldb"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  redis:
    image: redis
    container_name: "redis"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest