version: '3.7'
services:
  # web:
  #   build: .
  #   container_name: aspnet-core-webapi
  #   restart: always
  #   environment:
  #     - JWT_ISS=http://localhost:8181/api/signup
  #     - JWT_AUD=demo.api
  #     - JWT_EXPIRATION=1800
  #     - MONGO_URI=mongodb://mongodb:27017/clinfy
  #     - MYSQL_CONNECTION=Server=mysqldb;Database=dbz;User=root;Password=root;
  #     - REDIS_URI=redis,name=Demo.Api,defaultDatabase=1
  #   ports:
  #     - "8181:80"
  #   links:
  #     - mongodb
  #     - mysqldb
  #     - rabbitmq
  #     - redi
  #   depends_on:
  #     - mongodb
  #     - mysqldb
  #     - rabbitmq
  #     - redis
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - "27017:27017"
  mysqldb:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    container_name: "mysqldb"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest